# add this file
# default MySQL root password is 123456
# default remine user zzx, password admin

version: '3.8'

services:

  redmine:
    image: redmine
    container_name: redmine
    restart: always
    ports:
     - 9007:3000
    volumes: 
     - ./volumes/data/:/usr/src/redmine/files
     - ./volumes/plugins:/usr/src/redmine/plugins
     - ./volumes/themes:/usr/src/redmine/public/themes
     - ./volumes/config/configuration.yml:/usr/src/redmine/config/configuration.yml
    environment:
      REDMINE_DB_MYSQL: db
      REDMINE_DB_PASSWORD: 123456
      REDMINE_SECRET_KEY_BASE: supersecretkey
      REDMINE_PLUGINS_MIGRATE: "true"

  db:
    image: mysql:5.7
    container_name: redmine-mysql
    restart: always
    ports:
     - 3306:3306
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
     - ./volumes/mysql_config/conf.d:/etc/mysql/conf.d
     - ./volumes/mysql_data:/var/lib/mysql
     - ./volumes/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: redmine

networks:
  default:
      name: "apps"